version: "3.8"

services:
  produtos-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://0.0.0.0:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
